/* Generated by Yosys 0.7 (git sha1 61f6811, i686-w64-mingw32.static-gcc 4.9.3 -Os) */

module dff 
(Q, D, C, CLR, PRE, CE, NbarT, Si, global_reset); 

input D, C, CLR, PRE, CE, NbarT, Si, global_reset; 
output Q;
reg Q; 
reg val; 


always @(posedge C or posedge PRE or posedge CLR or posedge global_reset) begin
	if(CLR || global_reset)
		val = 1'b0;
	else	if(PRE)
		val = 1'b1;
	else	if(NbarT)
		val = Si; 
	else	if(CE)	val = D; 
end

always@(posedge val) Q =  val;
always@(negedge val) Q =  val;    
endmodule


module s344_scanInserted(CK, A0, A1, A2, A3, B0, B1, B2, B3, CNTVCO2, CNTVCON2, P0, P1, P2, P3, P4, P5, P6, P7, READY, START,  rst, Si, So, PbarS);
  
  input rst;
  input Si;
  output So;
  input PbarS;

  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  input A0;
  input A1;
  input A2;
  input A3;
  wire ACVG1VD1;
  wire ACVG2VD1;
  wire ACVG3VD1;
  wire ACVG4VD1;
  wire ACVQN0;
  wire ACVQN1;
  wire ACVQN2;
  wire ACVQN3;
  wire AM0;
  wire AM1;
  wire AM2;
  wire AM3;
  wire AX0;
  wire AX1;
  wire AX2;
  wire AX3;
  input B0;
  input B1;
  input B2;
  input B3;
  wire BMVS0N;
  input CK;
  wire CNTVCO0;
  output CNTVCO2;
  output CNTVCON2;
  wire CNTVG1VD;
  wire CNTVG2VD;
  wire CNTVG3VD;
  wire CT0;
  wire CT1;
  wire CT2;
  wire MRVG1VD;
  wire MRVG2VD;
  wire MRVG3VD;
  wire MRVG4VD;
  wire MRVQN0;
  wire MRVQN1;
  wire MRVQN2;
  wire MRVQN3;
  output P0;
  output P1;
  output P2;
  output P3;
  output P4;
  output P5;
  output P6;
  output P7;
  output READY;
  input START;

  NOT _199_ (
    .A(_050_),
    .Y(_051_)
  );
  NOT _200_ (
    .A(_122_),
    .Y(_128_)
  );
  NOT _201_ (
    .A(_131_),
    .Y(_134_)
  );
  NOT _202_ (
    .A(_138_),
    .Y(_149_)
  );
  NOT _203_ (
    .A(_165_),
    .Y(_179_)
  );
  NOT _204_ (
    .A(_052_),
    .Y(_062_)
  );
  NOT _205_ (
    .A(_072_),
    .Y(_081_)
  );
  NOT _206_ (
    .A(_090_),
    .Y(_099_)
  );
  NOT _207_ (
    .A(_109_),
    .Y(_137_)
  );
  NOT _208_ (
    .A(_121_),
    .Y(_139_)
  );
  NOR _209_ (
    .A(_123_),
    .B(_139_),
    .Y(_140_)
  );
  NOT _210_ (
    .A(_140_),
    .Y(_141_)
  );
  NOR _211_ (
    .A(_141_),
    .B(_137_),
    .Y(_124_)
  );
  NOT _212_ (
    .A(_123_),
    .Y(_143_)
  );
  NOR _213_ (
    .A(_143_),
    .B(_137_),
    .Y(_144_)
  );
  NOT _214_ (
    .A(_144_),
    .Y(_145_)
  );
  NOR _215_ (
    .A(_145_),
    .B(_139_),
    .Y(_125_)
  );
  NOT _216_ (
    .A(_125_),
    .Y(_126_)
  );
  NOT _217_ (
    .A(_129_),
    .Y(_148_)
  );
  NOR _218_ (
    .A(_148_),
    .B(_090_),
    .Y(_150_)
  );
  NAND _219_ (
    .A(_150_),
    .B(_149_),
    .Y(_151_)
  );
  NOT _220_ (
    .A(_130_),
    .Y(_153_)
  );
  NOR _221_ (
    .A(_153_),
    .B(_090_),
    .Y(_155_)
  );
  NOR _222_ (
    .A(_155_),
    .B(_134_),
    .Y(_157_)
  );
  NAND _223_ (
    .A(_130_),
    .B(_099_),
    .Y(_158_)
  );
  NOR _224_ (
    .A(_158_),
    .B(_131_),
    .Y(_159_)
  );
  NOR _225_ (
    .A(_159_),
    .B(_157_),
    .Y(_160_)
  );
  NAND _226_ (
    .A(_160_),
    .B(_151_),
    .Y(_162_)
  );
  NOR _227_ (
    .A(_123_),
    .B(_121_),
    .Y(_164_)
  );
  NOR _228_ (
    .A(_164_),
    .B(_109_),
    .Y(_166_)
  );
  NOR _229_ (
    .A(_140_),
    .B(_137_),
    .Y(_167_)
  );
  NOR _230_ (
    .A(_167_),
    .B(_166_),
    .Y(_169_)
  );
  NOR _231_ (
    .A(_160_),
    .B(_151_),
    .Y(_171_)
  );
  NOR _232_ (
    .A(_171_),
    .B(_169_),
    .Y(_172_)
  );
  NAND _233_ (
    .A(_172_),
    .B(_162_),
    .Y(_173_)
  );
  NOT _234_ (
    .A(_169_),
    .Y(_175_)
  );
  NOR _235_ (
    .A(_175_),
    .B(_149_),
    .Y(_177_)
  );
  NOR _236_ (
    .A(_177_),
    .B(_127_),
    .Y(_178_)
  );
  NAND _237_ (
    .A(_178_),
    .B(_173_),
    .Y(_132_)
  );
  NAND _238_ (
    .A(_133_),
    .B(_099_),
    .Y(_181_)
  );
  NOR _239_ (
    .A(_181_),
    .B(_122_),
    .Y(_182_)
  );
  NOT _240_ (
    .A(_182_),
    .Y(_184_)
  );
  NAND _241_ (
    .A(_181_),
    .B(_122_),
    .Y(_186_)
  );
  NAND _242_ (
    .A(_186_),
    .B(_184_),
    .Y(_188_)
  );
  NOR _243_ (
    .A(_157_),
    .B(_151_),
    .Y(_190_)
  );
  NOR _244_ (
    .A(_190_),
    .B(_159_),
    .Y(_192_)
  );
  NAND _245_ (
    .A(_192_),
    .B(_188_),
    .Y(_194_)
  );
  NOT _246_ (
    .A(_186_),
    .Y(_196_)
  );
  NOR _247_ (
    .A(_192_),
    .B(_196_),
    .Y(_198_)
  );
  NAND _248_ (
    .A(_198_),
    .B(_184_),
    .Y(_053_)
  );
  NAND _249_ (
    .A(_053_),
    .B(_194_),
    .Y(_054_)
  );
  NAND _250_ (
    .A(_054_),
    .B(_175_),
    .Y(_055_)
  );
  NOR _251_ (
    .A(_175_),
    .B(_134_),
    .Y(_056_)
  );
  NOR _252_ (
    .A(_056_),
    .B(_127_),
    .Y(_057_)
  );
  NAND _253_ (
    .A(_057_),
    .B(_055_),
    .Y(_135_)
  );
  NOR _254_ (
    .A(_198_),
    .B(_182_),
    .Y(_058_)
  );
  NAND _255_ (
    .A(_136_),
    .B(_099_),
    .Y(_059_)
  );
  NOR _256_ (
    .A(_059_),
    .B(_050_),
    .Y(_060_)
  );
  NOR _257_ (
    .A(_060_),
    .B(_169_),
    .Y(_061_)
  );
  NAND _258_ (
    .A(_061_),
    .B(_058_),
    .Y(_063_)
  );
  NOR _259_ (
    .A(_059_),
    .B(_169_),
    .Y(_064_)
  );
  NOR _260_ (
    .A(_064_),
    .B(_051_),
    .Y(_065_)
  );
  NOR _261_ (
    .A(_065_),
    .B(_127_),
    .Y(_066_)
  );
  NAND _262_ (
    .A(_066_),
    .B(_063_),
    .Y(_142_)
  );
  NOT _263_ (
    .A(_059_),
    .Y(_067_)
  );
  NOR _264_ (
    .A(_067_),
    .B(_051_),
    .Y(_068_)
  );
  NOR _265_ (
    .A(_068_),
    .B(_060_),
    .Y(_069_)
  );
  NAND _266_ (
    .A(_069_),
    .B(_058_),
    .Y(_070_)
  );
  NOR _267_ (
    .A(_069_),
    .B(_058_),
    .Y(_071_)
  );
  NOR _268_ (
    .A(_071_),
    .B(_169_),
    .Y(_073_)
  );
  NAND _269_ (
    .A(_073_),
    .B(_070_),
    .Y(_074_)
  );
  NOR _270_ (
    .A(_175_),
    .B(_128_),
    .Y(_075_)
  );
  NOR _271_ (
    .A(_075_),
    .B(_127_),
    .Y(_076_)
  );
  NAND _272_ (
    .A(_076_),
    .B(_074_),
    .Y(_146_)
  );
  NOT _273_ (
    .A(_127_),
    .Y(_077_)
  );
  NAND _274_ (
    .A(_145_),
    .B(_139_),
    .Y(_078_)
  );
  NAND _275_ (
    .A(_078_),
    .B(_077_),
    .Y(_079_)
  );
  NOR _276_ (
    .A(_079_),
    .B(_125_),
    .Y(_147_)
  );
  NOR _277_ (
    .A(_167_),
    .B(_123_),
    .Y(_080_)
  );
  NAND _278_ (
    .A(_145_),
    .B(_077_),
    .Y(_082_)
  );
  NOR _279_ (
    .A(_082_),
    .B(_080_),
    .Y(_152_)
  );
  NOR _280_ (
    .A(_167_),
    .B(_127_),
    .Y(_154_)
  );
  NAND _281_ (
    .A(_124_),
    .B(_165_),
    .Y(_083_)
  );
  NOT _282_ (
    .A(_156_),
    .Y(_084_)
  );
  NOT _283_ (
    .A(_124_),
    .Y(_085_)
  );
  NAND _284_ (
    .A(_085_),
    .B(_084_),
    .Y(_086_)
  );
  NAND _285_ (
    .A(_086_),
    .B(_083_),
    .Y(_087_)
  );
  NAND _286_ (
    .A(_087_),
    .B(_169_),
    .Y(_088_)
  );
  NOT _287_ (
    .A(_150_),
    .Y(_089_)
  );
  NAND _288_ (
    .A(_089_),
    .B(_138_),
    .Y(_091_)
  );
  NAND _289_ (
    .A(_091_),
    .B(_151_),
    .Y(_092_)
  );
  NAND _290_ (
    .A(_092_),
    .B(_175_),
    .Y(_093_)
  );
  NAND _291_ (
    .A(_093_),
    .B(_088_),
    .Y(_161_)
  );
  NOR _292_ (
    .A(_169_),
    .B(_165_),
    .Y(_094_)
  );
  NOR _293_ (
    .A(_124_),
    .B(_163_),
    .Y(_095_)
  );
  NAND _294_ (
    .A(_124_),
    .B(_052_),
    .Y(_096_)
  );
  NAND _295_ (
    .A(_096_),
    .B(_169_),
    .Y(_097_)
  );
  NOR _296_ (
    .A(_097_),
    .B(_095_),
    .Y(_098_)
  );
  NOR _297_ (
    .A(_098_),
    .B(_094_),
    .Y(_168_)
  );
  NOR _298_ (
    .A(_169_),
    .B(_052_),
    .Y(_100_)
  );
  NOR _299_ (
    .A(_124_),
    .B(_170_),
    .Y(_101_)
  );
  NAND _300_ (
    .A(_124_),
    .B(_072_),
    .Y(_102_)
  );
  NAND _301_ (
    .A(_102_),
    .B(_169_),
    .Y(_103_)
  );
  NOR _302_ (
    .A(_103_),
    .B(_101_),
    .Y(_104_)
  );
  NOR _303_ (
    .A(_104_),
    .B(_100_),
    .Y(_174_)
  );
  NOR _304_ (
    .A(_169_),
    .B(_072_),
    .Y(_105_)
  );
  NOR _305_ (
    .A(_124_),
    .B(_176_),
    .Y(_106_)
  );
  NAND _306_ (
    .A(_124_),
    .B(_090_),
    .Y(_107_)
  );
  NAND _307_ (
    .A(_107_),
    .B(_169_),
    .Y(_108_)
  );
  NOR _308_ (
    .A(_108_),
    .B(_106_),
    .Y(_110_)
  );
  NOR _309_ (
    .A(_110_),
    .B(_105_),
    .Y(_180_)
  );
  NAND _310_ (
    .A(_164_),
    .B(_137_),
    .Y(_111_)
  );
  NOT _311_ (
    .A(_111_),
    .Y(_112_)
  );
  NOR _312_ (
    .A(_112_),
    .B(_136_),
    .Y(_113_)
  );
  NOR _313_ (
    .A(_111_),
    .B(_183_),
    .Y(_114_)
  );
  NOR _314_ (
    .A(_114_),
    .B(_113_),
    .Y(_185_)
  );
  NOR _315_ (
    .A(_112_),
    .B(_133_),
    .Y(_115_)
  );
  NOR _316_ (
    .A(_111_),
    .B(_187_),
    .Y(_116_)
  );
  NOR _317_ (
    .A(_116_),
    .B(_115_),
    .Y(_189_)
  );
  NOR _318_ (
    .A(_112_),
    .B(_130_),
    .Y(_117_)
  );
  NOR _319_ (
    .A(_111_),
    .B(_191_),
    .Y(_118_)
  );
  NOR _320_ (
    .A(_118_),
    .B(_117_),
    .Y(_193_)
  );
  NOR _321_ (
    .A(_112_),
    .B(_129_),
    .Y(_119_)
  );
  NOR _322_ (
    .A(_111_),
    .B(_195_),
    .Y(_120_)
  );
  NOR _323_ (
    .A(_120_),
    .B(_119_),
    .Y(_197_)
  );

  dff DFF_0 (
    .C(CK),
    .CE(1'b1),
    .CLR(rst),
    .D(CNTVG3VD),
    .NbarT(PbarS),
    .PRE(1'b0),
    .Q(CT2),
    .Si(Si),
    .global_reset(1'b0)
  );

  dff DFF_1 (
    .C(CK),
    .CE(1'b1),
    .CLR(rst),
    .D(CNTVG2VD),
    .NbarT(PbarS),
    .PRE(1'b0),
    .Q(CT1),
    .Si(CT2),
    .global_reset(1'b0)
  );

  dff DFF_10 (
    .C(CK),
    .CE(1'b1),
    .CLR(rst),
    .D(MRVG1VD),
    .NbarT(PbarS),
    .PRE(1'b0),
    .Q(MRVQN0),
    .Si(CT1),
    .global_reset(1'b0)
  );

  dff DFF_11 (
    .C(CK),
    .CE(1'b1),
    .CLR(rst),
    .D(AM3),
    .NbarT(PbarS),
    .PRE(1'b0),
    .Q(AX3),
    .Si(MRVQN0),
    .global_reset(1'b0)
  );

  dff DFF_12 (
    .C(CK),
    .CE(1'b1),
    .CLR(rst),
    .D(AM2),
    .NbarT(PbarS),
    .PRE(1'b0),
    .Q(AX2),
    .Si(AX3),
    .global_reset(1'b0)
  );

  dff DFF_13 (
    .C(CK),
    .CE(1'b1),
    .CLR(rst),
    .D(AM1),
    .NbarT(PbarS),
    .PRE(1'b0),
    .Q(AX1),
    .Si(AX2),
    .global_reset(1'b0)
  );

  dff DFF_14 (
    .C(CK),
    .CE(1'b1),
    .CLR(rst),
    .D(AM0),
    .NbarT(PbarS),
    .PRE(1'b0),
    .Q(AX0),
    .Si(AX1),
    .global_reset(1'b0)
  );

  dff DFF_2 (
    .C(CK),
    .CE(1'b1),
    .CLR(rst),
    .D(CNTVG1VD),
    .NbarT(PbarS),
    .PRE(1'b0),
    .Q(CNTVCO0),
    .Si(AX0),
    .global_reset(1'b0)
  );

  dff DFF_3 (
    .C(CK),
    .CE(1'b1),
    .CLR(rst),
    .D(ACVG4VD1),
    .NbarT(PbarS),
    .PRE(1'b0),
    .Q(ACVQN3),
    .Si(CNTVCO0),
    .global_reset(1'b0)
  );

  dff DFF_4 (
    .C(CK),
    .CE(1'b1),
    .CLR(rst),
    .D(ACVG3VD1),
    .NbarT(PbarS),
    .PRE(1'b0),
    .Q(ACVQN2),
    .Si(ACVQN3),
    .global_reset(1'b0)
  );

  dff DFF_5 (
    .C(CK),
    .CE(1'b1),
    .CLR(rst),
    .D(ACVG2VD1),
    .NbarT(PbarS),
    .PRE(1'b0),
    .Q(ACVQN1),
    .Si(ACVQN2),
    .global_reset(1'b0)
  );

  dff DFF_6 (
    .C(CK),
    .CE(1'b1),
    .CLR(rst),
    .D(ACVG1VD1),
    .NbarT(PbarS),
    .PRE(1'b0),
    .Q(ACVQN0),
    .Si(ACVQN1),
    .global_reset(1'b0)
  );

  dff DFF_7 (
    .C(CK),
    .CE(1'b1),
    .CLR(rst),
    .D(MRVG4VD),
    .NbarT(PbarS),
    .PRE(1'b0),
    .Q(MRVQN3),
    .Si(ACVQN0),
    .global_reset(1'b0)
  );

  dff DFF_8 (
    .C(CK),
    .CE(1'b1),
    .CLR(rst),
    .D(MRVG3VD),
    .NbarT(PbarS),
    .PRE(1'b0),
    .Q(MRVQN2),
    .Si(MRVQN3),
    .global_reset(1'b0)
  );

  dff DFF_9 (
    .C(CK),
    .CE(1'b1),
    .CLR(rst),
    .D(MRVG2VD),
    .NbarT(PbarS),
    .PRE(1'b0),
    .Q(MRVQN1),
    .Si(MRVQN2),
    .global_reset(1'b0)
  );
  assign So = MRVQN1;

  assign BMVS0N = READY;
  assign CT0 = CNTVCO0;
  assign _050_ = ACVQN3;
  assign P7 = _051_;
  assign _122_ = ACVQN2;
  assign P6 = _128_;
  assign _131_ = ACVQN1;
  assign P5 = _134_;
  assign _138_ = ACVQN0;
  assign P4 = _149_;
  assign _165_ = MRVQN3;
  assign P3 = _179_;
  assign _052_ = MRVQN2;
  assign P2 = _062_;
  assign _072_ = MRVQN1;
  assign P1 = _081_;
  assign _090_ = MRVQN0;
  assign P0 = _099_;
  assign _109_ = CNTVCO0;
  assign _121_ = CT2;
  assign _123_ = CT1;
  assign READY = _124_;
  assign CNTVCO2 = _125_;
  assign CNTVCON2 = _126_;
  assign _127_ = START;
  assign _129_ = AX0;
  assign _130_ = AX1;
  assign ACVG1VD1 = _132_;
  assign _133_ = AX2;
  assign ACVG2VD1 = _135_;
  assign _136_ = AX3;
  assign ACVG4VD1 = _142_;
  assign ACVG3VD1 = _146_;
  assign CNTVG3VD = _147_;
  assign CNTVG2VD = _152_;
  assign CNTVG1VD = _154_;
  assign _156_ = B3;
  assign MRVG4VD = _161_;
  assign _163_ = B2;
  assign MRVG3VD = _168_;
  assign _170_ = B1;
  assign MRVG2VD = _174_;
  assign _176_ = B0;
  assign MRVG1VD = _180_;
  assign _183_ = A3;
  assign AM3 = _185_;
  assign _187_ = A2;
  assign AM2 = _189_;
  assign _191_ = A1;
  assign AM1 = _193_;
  assign _195_ = A0;
  assign AM0 = _197_;
endmodule
