/* Generated by Yosys 0.7 (git sha1 61f6811, i686-w64-mingw32.static-gcc 4.9.3 -Os) */

module custom(clk, A, B, C, D, Y0, Y1);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  input A;
  input B;
  input C;
  input D;
  output Y0;
  output Y1;
  input clk;
  wire w1;
  wire w3;
  wire w4;
  wire w5;
  NAND _14_ (
    .A(_04_),
    .B(_03_),
    .Y(_09_)
  );
  NAND _15_ (
    .A(_09_),
    .B(_11_),
    .Y(_07_)
  );
  NAND _16_ (
    .A(_07_),
    .B(_10_),
    .Y(_12_)
  );
  NAND _17_ (
    .A(_07_),
    .B(_13_),
    .Y(_08_)
  );
  NAND _18_ (
    .A(_08_),
    .B(_05_),
    .Y(_06_)
  );
 dff DFF_0(
 	.C(CK),
 	.CE(1'b1),
 	.CLR(rst),
 	.D(w1),
 	.NbarT(PbarS),
 	.PRE(1'b0),
 	.Q(w5),
 	.Si(Si),
 	.global_reset(1'b0)
 );

 dff DFF_1(
 	.C(CK),
 	.CE(1'b1),
 	.CLR(rst),
 	.D(w3),
 	.NbarT(PbarS),
 	.PRE(1'b0),
 	.Q(w4),
 	.Si(w5),
 	.global_reset(1'b0)
 );

  assign Y0 = w5;
  assign _03_ = B;
  assign _04_ = A;
  assign w1 = _09_;
  assign _10_ = D;
  assign _11_ = C;
  assign w3 = _12_;
  assign _13_ = w4;
  assign _05_ = w5;
  assign Y1 = _06_;
endmodule

module dff(CK, Q, D);
  input CK;
  input D;
  output Q;
  DFF _0_ (
    .C(CK),
    .D(D),
    .Q(Q)
  );
endmodule
