/* Generated by Yosys 0.7 (git sha1 61f6811, i686-w64-mingw32.static-gcc 4.9.3 -Os) */

module mine(a, b, c, d, e, y1, y2, y3);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  input a;
  input b;
  input c;
  input d;
  input e;
  output y1;
  output y2;
  output y3;
  NAND _22_ (
    .A(_18_),
    .B(_08_),
    .Y(_21_)
  );
  NOT _23_ (
    .A(_19_),
    .Y(_10_)
  );
  NOT _24_ (
    .A(_20_),
    .Y(_11_)
  );
  NOR _25_ (
    .A(_11_),
    .B(_10_),
    .Y(_12_)
  );
  NAND _26_ (
    .A(_12_),
    .B(_21_),
    .Y(_09_)
  );
  NOR _27_ (
    .A(_18_),
    .B(_08_),
    .Y(_15_)
  );
  NAND _28_ (
    .A(_11_),
    .B(_10_),
    .Y(_17_)
  );
  NOR _29_ (
    .A(_17_),
    .B(_15_),
    .Y(_13_)
  );
  NOT _30_ (
    .A(_14_),
    .Y(_16_)
  );
  assign _08_ = a;
  assign _18_ = b;
  assign _19_ = c;
  assign _20_ = d;
  assign y1 = _09_;
  assign y2 = _13_;
  assign _14_ = e;
  assign y3 = _16_;
endmodule
