/* Generated by Yosys 0.7 (git sha1 61f6811, i686-w64-mingw32.static-gcc 4.9.3 -Os) */

module dff(CK, Q, D);
  input CK;
  input D;
  output Q;
  DFF _0_ (
    .C(CK),
    .D(D),
    .Q(Q)
  );
endmodule

module s27(GND, VDD, CK, G0, G1, G17, G2, G3);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _30_;
  wire _31_;
  input CK;
  input G0;
  input G1;
  wire G10;
  wire G11;
  wire G13;
  output G17;
  input G2;
  input G3;
  wire G5;
  wire G6;
  wire G7;
  input GND;
  input VDD;
  NOR _32_ (
    .A(_21_),
    .B(_14_),
    .Y(_23_)
  );
  NOR _33_ (
    .A(_23_),
    .B(_08_),
    .Y(_13_)
  );
  NOR _34_ (
    .A(_13_),
    .B(_10_),
    .Y(_09_)
  );
  NOT _35_ (
    .A(_08_),
    .Y(_24_)
  );
  NOT _36_ (
    .A(_14_),
    .Y(_25_)
  );
  NOR _37_ (
    .A(_30_),
    .B(_29_),
    .Y(_26_)
  );
  NAND _38_ (
    .A(_26_),
    .B(_31_),
    .Y(_27_)
  );
  NAND _39_ (
    .A(_27_),
    .B(_25_),
    .Y(_28_)
  );
  NAND _40_ (
    .A(_28_),
    .B(_24_),
    .Y(_11_)
  );
  NOR _41_ (
    .A(_26_),
    .B(_15_),
    .Y(_18_)
  );
  NOT _42_ (
    .A(_07_),
    .Y(_10_)
  );
  NOT _43_ (
    .A(_22_),
    .Y(_12_)
  );
  NOR _44_ (
    .A(_12_),
    .B(_07_),
    .Y(_14_)
  );
  NOT _45_ (
    .A(_31_),
    .Y(_16_)
  );
  NOT _46_ (
    .A(_29_),
    .Y(_17_)
  );
  NOT _47_ (
    .A(_30_),
    .Y(_19_)
  );
  NAND _48_ (
    .A(_19_),
    .B(_17_),
    .Y(_20_)
  );
  NOR _49_ (
    .A(_20_),
    .B(_16_),
    .Y(_21_)
  );
  dff DFF_0 (
    .CK(CK),
    .D(G10),
    .Q(G5)
  );
  dff DFF_1 (
    .CK(CK),
    .D(G11),
    .Q(G6)
  );
  dff DFF_2 (
    .CK(CK),
    .D(G13),
    .Q(G7)
  );
  assign _07_ = G0;
  assign _22_ = G6;
  assign _29_ = G7;
  assign _30_ = G1;
  assign _31_ = G3;
  assign _08_ = G5;
  assign G10 = _09_;
  assign G17 = _11_;
  assign G11 = _13_;
  assign _15_ = G2;
  assign G13 = _18_;
endmodule
